-- =============================================================
-- VESTA - DDL - Criação das Tabelas
-- Disciplina: Mastering Relational and Non-Relational Database
-- FIAP Global Solution 2026/1
-- =============================================================
-- Este script é idempotente: remove tabelas Vesta existentes
-- (de runs anteriores com falha) antes de recriá-las.
-- =============================================================

-- Remove tabelas Vesta na ordem inversa de dependência FK
BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'TB_ALERTA',
      'TB_TRANSFERENCIA_ABRIGO',
      'TB_MOVIMENTACAO_RECURSO',
      'TB_SOLICITACAO_RECURSO',
      'TB_OCORRENCIA',
      'TB_ESTOQUE_ABRIGO',
      'TB_RECURSO',
      'TB_PESSOA_ABRIGADA',
      'TB_FAMILIA',
      'TB_USUARIO',
      'TB_ABRIGO',
      'TB_PERFIL_ACESSO',
      'TB_INSTITUICAO',
      'TB_REGIAO'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- 1. TB_REGIAO
CREATE TABLE TB_REGIAO (
    id_regiao       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_regiao       VARCHAR2(100) NOT NULL,
    sg_estado       CHAR(2)       NOT NULL,
    dt_criacao      DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT VESTA_uq_regiao_nm UNIQUE (nm_regiao)
);

-- 2. TB_INSTITUICAO
CREATE TABLE TB_INSTITUICAO (
    id_instituicao  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_instituicao  VARCHAR2(150) NOT NULL,
    tp_instituicao  VARCHAR2(50)  NOT NULL,
    id_regiao       NUMBER        NOT NULL,
    dt_criacao      DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT VESTA_fk_inst_regiao    FOREIGN KEY (id_regiao) REFERENCES TB_REGIAO(id_regiao),
    CONSTRAINT VESTA_ck_inst_tp        CHECK (tp_instituicao IN ('PREFEITURA','DEFESA_CIVIL','GOVERNO_ESTADUAL','ONG'))
);

-- 3. TB_PERFIL_ACESSO
CREATE TABLE TB_PERFIL_ACESSO (
    id_perfil       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_perfil       VARCHAR2(50)  NOT NULL,
    ds_permissoes   VARCHAR2(500),
    CONSTRAINT VESTA_uq_perfil_nm UNIQUE (nm_perfil),
    CONSTRAINT VESTA_ck_perfil_nm CHECK (nm_perfil IN ('ADMIN','GESTOR','OPERADOR'))
);

-- 4. TB_ABRIGO
CREATE TABLE TB_ABRIGO (
    id_abrigo             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_abrigo             VARCHAR2(150) NOT NULL,
    ds_endereco           VARCHAR2(300) NOT NULL,
    qt_capacidade_maxima  NUMBER        NOT NULL,
    qt_ocupacao_atual     NUMBER        DEFAULT 0 NOT NULL,
    st_status             VARCHAR2(20)  DEFAULT 'ATIVO' NOT NULL,
    id_regiao             NUMBER        NOT NULL,
    id_instituicao        NUMBER        NOT NULL,
    dt_abertura           DATE          DEFAULT SYSDATE NOT NULL,
    dt_criacao            DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT VESTA_fk_abrigo_regiao  FOREIGN KEY (id_regiao)      REFERENCES TB_REGIAO(id_regiao),
    CONSTRAINT VESTA_fk_abrigo_inst    FOREIGN KEY (id_instituicao)  REFERENCES TB_INSTITUICAO(id_instituicao),
    CONSTRAINT VESTA_ck_abrigo_status  CHECK (st_status IN ('ATIVO','LOTADO','INTERDITADO','INATIVO')),
    CONSTRAINT VESTA_ck_abrigo_ocup    CHECK (qt_ocupacao_atual >= 0),
    CONSTRAINT VESTA_ck_abrigo_cap     CHECK (qt_capacidade_maxima > 0)
);

-- 5. TB_USUARIO
CREATE TABLE TB_USUARIO (
    id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_usuario      VARCHAR2(150) NOT NULL,
    ds_email        VARCHAR2(200) NOT NULL,
    ds_senha_hash   VARCHAR2(255) NOT NULL,
    id_perfil       NUMBER        NOT NULL,
    id_abrigo       NUMBER,
    st_ativo        CHAR(1)       DEFAULT 'S' NOT NULL,
    dt_criacao      DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT VESTA_fk_usuario_perfil FOREIGN KEY (id_perfil)  REFERENCES TB_PERFIL_ACESSO(id_perfil),
    CONSTRAINT VESTA_fk_usuario_abrigo FOREIGN KEY (id_abrigo)  REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_uq_usuario_email  UNIQUE (ds_email),
    CONSTRAINT VESTA_ck_usuario_ativo  CHECK (st_ativo IN ('S','N'))
);

-- 6. TB_FAMILIA
CREATE TABLE TB_FAMILIA (
    id_familia          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_responsavel      VARCHAR2(150) NOT NULL,
    nr_cpf_responsavel  VARCHAR2(14),
    nr_telefone         VARCHAR2(20),
    id_abrigo           NUMBER        NOT NULL,
    dt_entrada          DATE          DEFAULT SYSDATE NOT NULL,
    dt_saida            DATE,
    CONSTRAINT VESTA_fk_familia_abrigo FOREIGN KEY (id_abrigo) REFERENCES TB_ABRIGO(id_abrigo)
);

-- 7. TB_PESSOA_ABRIGADA
CREATE TABLE TB_PESSOA_ABRIGADA (
    id_pessoa       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_pessoa       VARCHAR2(150) NOT NULL,
    dt_nascimento   DATE,
    tp_documento    VARCHAR2(20),
    nr_documento    VARCHAR2(30),
    id_familia      NUMBER        NOT NULL,
    id_abrigo       NUMBER        NOT NULL,
    st_presente     CHAR(1)       DEFAULT 'S' NOT NULL,
    dt_entrada      DATE          DEFAULT SYSDATE NOT NULL,
    dt_saida        DATE,
    CONSTRAINT VESTA_fk_pessoa_familia FOREIGN KEY (id_familia) REFERENCES TB_FAMILIA(id_familia),
    CONSTRAINT VESTA_fk_pessoa_abrigo  FOREIGN KEY (id_abrigo)  REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_ck_pessoa_pres    CHECK (st_presente IN ('S','N'))
);

-- 8. TB_RECURSO
CREATE TABLE TB_RECURSO (
    id_recurso          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_recurso          VARCHAR2(150) NOT NULL,
    tp_recurso          VARCHAR2(50)  NOT NULL,
    ds_unidade_medida   VARCHAR2(30)  NOT NULL,
    CONSTRAINT VESTA_uq_recurso_nm UNIQUE (nm_recurso),
    CONSTRAINT VESTA_ck_recurso_tp CHECK (tp_recurso IN ('ALIMENTO','AGUA','MEDICAMENTO','HIGIENE','VESTUARIO','EQUIPAMENTO'))
);

-- 9. TB_ESTOQUE_ABRIGO
CREATE TABLE TB_ESTOQUE_ABRIGO (
    id_estoque      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_abrigo       NUMBER  NOT NULL,
    id_recurso      NUMBER  NOT NULL,
    qt_atual        NUMBER  DEFAULT 0 NOT NULL,
    qt_minima       NUMBER  NOT NULL,
    dt_atualizacao  DATE    DEFAULT SYSDATE NOT NULL,
    CONSTRAINT VESTA_fk_est_abrigo  FOREIGN KEY (id_abrigo)  REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_fk_est_recurso FOREIGN KEY (id_recurso) REFERENCES TB_RECURSO(id_recurso),
    CONSTRAINT VESTA_uq_est_abr_rec UNIQUE (id_abrigo, id_recurso),
    CONSTRAINT VESTA_ck_est_qt      CHECK (qt_atual >= 0)
);

-- 10. TB_OCORRENCIA
CREATE TABLE TB_OCORRENCIA (
    id_ocorrencia   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_abrigo       NUMBER        NOT NULL,
    id_usuario      NUMBER        NOT NULL,
    nm_titulo       VARCHAR2(200) NOT NULL,
    ds_descricao    CLOB,
    tp_severidade   VARCHAR2(20)  NOT NULL,
    st_status       VARCHAR2(20)  DEFAULT 'ABERTA' NOT NULL,
    dt_ocorrencia   DATE          DEFAULT SYSDATE NOT NULL,
    dt_resolucao    DATE,
    CONSTRAINT VESTA_fk_ocorr_abrigo   FOREIGN KEY (id_abrigo)  REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_fk_ocorr_usuario  FOREIGN KEY (id_usuario) REFERENCES TB_USUARIO(id_usuario),
    CONSTRAINT VESTA_ck_ocorr_sev      CHECK (tp_severidade IN ('BAIXA','MEDIA','ALTA','CRITICA')),
    CONSTRAINT VESTA_ck_ocorr_status   CHECK (st_status IN ('ABERTA','EM_ANDAMENTO','RESOLVIDA'))
);

-- 11. TB_SOLICITACAO_RECURSO
CREATE TABLE TB_SOLICITACAO_RECURSO (
    id_solicitacao          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_abrigo               NUMBER        NOT NULL,
    id_recurso              NUMBER        NOT NULL,
    id_usuario_solicitante  NUMBER        NOT NULL,
    qt_solicitada           NUMBER        NOT NULL,
    st_status               VARCHAR2(20)  DEFAULT 'ABERTA' NOT NULL,
    ds_justificativa        VARCHAR2(500),
    dt_solicitacao          DATE          DEFAULT SYSDATE NOT NULL,
    dt_atualizacao          DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT VESTA_fk_solic_abrigo   FOREIGN KEY (id_abrigo)              REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_fk_solic_recurso  FOREIGN KEY (id_recurso)             REFERENCES TB_RECURSO(id_recurso),
    CONSTRAINT VESTA_fk_solic_usuario  FOREIGN KEY (id_usuario_solicitante) REFERENCES TB_USUARIO(id_usuario),
    CONSTRAINT VESTA_ck_solic_status   CHECK (st_status IN ('ABERTA','EM_ANALISE','EM_ATENDIMENTO','CONCLUIDA','CANCELADA'))
);

-- 12. TB_MOVIMENTACAO_RECURSO
CREATE TABLE TB_MOVIMENTACAO_RECURSO (
    id_movimentacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitacao  NUMBER,
    id_abrigo       NUMBER        NOT NULL,
    id_recurso      NUMBER        NOT NULL,
    id_usuario      NUMBER        NOT NULL,
    tp_movimentacao VARCHAR2(20)  NOT NULL,
    qt_movimentada  NUMBER        NOT NULL,
    ds_observacao   VARCHAR2(500),
    dt_movimentacao DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT VESTA_fk_mov_solic   FOREIGN KEY (id_solicitacao) REFERENCES TB_SOLICITACAO_RECURSO(id_solicitacao),
    CONSTRAINT VESTA_fk_mov_abrigo  FOREIGN KEY (id_abrigo)      REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_fk_mov_recurso FOREIGN KEY (id_recurso)     REFERENCES TB_RECURSO(id_recurso),
    CONSTRAINT VESTA_fk_mov_usuario FOREIGN KEY (id_usuario)     REFERENCES TB_USUARIO(id_usuario),
    CONSTRAINT VESTA_ck_mov_tp      CHECK (tp_movimentacao IN ('ENTRADA','SAIDA','AJUSTE'))
);

-- 13. TB_TRANSFERENCIA_ABRIGO
CREATE TABLE TB_TRANSFERENCIA_ABRIGO (
    id_transferencia        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_abrigo_origem        NUMBER        NOT NULL,
    id_abrigo_destino       NUMBER        NOT NULL,
    id_familia              NUMBER        NOT NULL,
    id_usuario_responsavel  NUMBER        NOT NULL,
    ds_motivo               VARCHAR2(500),
    st_status               VARCHAR2(20)  DEFAULT 'PENDENTE' NOT NULL,
    dt_solicitacao          DATE          DEFAULT SYSDATE NOT NULL,
    dt_conclusao            DATE,
    CONSTRAINT VESTA_fk_trf_origem  FOREIGN KEY (id_abrigo_origem)       REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_fk_trf_destino FOREIGN KEY (id_abrigo_destino)      REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_fk_trf_familia FOREIGN KEY (id_familia)             REFERENCES TB_FAMILIA(id_familia),
    CONSTRAINT VESTA_fk_trf_usuario FOREIGN KEY (id_usuario_responsavel) REFERENCES TB_USUARIO(id_usuario),
    CONSTRAINT VESTA_ck_trf_status  CHECK (st_status IN ('PENDENTE','APROVADA','CONCLUIDA','CANCELADA')),
    CONSTRAINT VESTA_ck_trf_abrigos CHECK (id_abrigo_origem <> id_abrigo_destino)
);

-- 14. TB_ALERTA
CREATE TABLE TB_ALERTA (
    id_alerta       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_abrigo       NUMBER        NOT NULL,
    tp_alerta       VARCHAR2(50)  NOT NULL,
    ds_mensagem     VARCHAR2(500) NOT NULL,
    st_status       VARCHAR2(20)  DEFAULT 'ATIVO' NOT NULL,
    dt_geracao      DATE          DEFAULT SYSDATE NOT NULL,
    dt_resolucao    DATE,
    CONSTRAINT VESTA_fk_alerta_abrigo FOREIGN KEY (id_abrigo) REFERENCES TB_ABRIGO(id_abrigo),
    CONSTRAINT VESTA_ck_alerta_tp     CHECK (tp_alerta IN ('LOTACAO','ESTOQUE_CRITICO','OCORRENCIA_CRITICA')),
    CONSTRAINT VESTA_ck_alerta_status CHECK (st_status IN ('ATIVO','RESOLVIDO'))
);
